name: CI (mcp-servers)

on:
  push:
    paths:
      - 'mcp-servers/**'
      - '.github/workflows/test-mcp-servers.yml'
  pull_request:
    paths:
      - 'mcp-servers/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest ruff black
      - name: Lint
        working-directory: mcp-servers
        run: |
          make lint
      - name: Tests
        working-directory: mcp-servers
        run: |
          make test

